url: https://jonlee.github.io
baseurl: /Travel-Trails

# Site settings
title: Travel Trails
email: 
description: "Collect 3D models of famous and historic landmarks. These 3D models form your Travel Trails collection. Relive your memories by interacting with the high resolution models and exploring sites like you've never seen before."
icon: ðŸ—ºï¸

# Team names, titles and social links
people:
- name: Austin Theriault
  pic: 1
  position: Backend Design
  description: >
    
  social:
    - title: github
      url: https://github.com/ajbt200128
    - title: linkedin
      url: https://www.linkedin.com/in/austin-theriault-1648b2168/

- name: Jonathan Lee
  pic: 2
  position: 3D Reconstruction
  description: >
    Jonathan is a senior at GW and will be graduating with a B.S. in Computer Science.
    He has worked as a Teaching Assistant at GW and has been an active member of Design/Build/Fly.
    After graduating, he will be starting a two year Masters in Robotics program to pursue his interest in
    robotic perception and autonomy.
    <br>
    <br>
    For Travel Trails, Jonathan worked on utilizing 3D reconstruction software (COLMAP) to create
    high resolution point clouds generated from user and internet images.
  social:
    - title: github
      url: https://github.com/jonlee48
    - title: linkedin
      url: https://www.linkedin.com/in/jonlee48/

- name: Ryan Hudson
  pic: 3
  position: App Design
  description: >
    Ryan Hudson is a senior at GW and will be graduating with a B.S. in Computer Science and a minor in Psychology. 
    During his time at GW, he completed a non-technical track in Law & Crime and interned at the US District Court for the District of Columbia. 
    After graduating, he will be pursuing a Juris Doctor and subsequently, a career in patent law.
    <br>
    <br>
    For Travel Trails, Ryan worked on front end development, designing and building the Android application that users interact with.
  social:
    - title: github
      url: https://github.com/rhudson11
    - title: linkedin
      url: https://www.linkedin.com/in/ryan-hudson-297b8017a/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/jonlee48/Travel-Trails

# Postal address (add as many lines as necessary)
address:
  - line: 800 22nd St NW 
  - line: Washington, DC 20052

# Build settings
markdown: kramdown
permalink: pretty